/**
 * cbodyTest.java
 *
 * This file was generated by XMLSpy 2010 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.cbodyTest;

import com.altova.*;
import com.altova.types.*;
import com.cbody.*;

public class cbodyTest {
    protected void example() throws Exception {

        com.cbody.cbody2 doc = com.cbody.cbody2.loadFromFile(getClass().getClassLoader().getResource("cbody.xml").getFile());
        String s = doc.saveToString(true);
        System.out.println("s = " + s);
    }

    public static void main(String args[]) {
        try {
            System.out.println("cbody Test Application");
            new cbodyTest().example();
            System.out.println("OK");
            System.exit(0);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }
    }
}
