/**
 * cbodyTest.java
 *
 * This file was generated by XMLSpy 2010 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.cbodyTest;

import com.altova.*;
import com.altova.types.*;
import com.cbody.*;

public class cbodyTest {
	protected static void example() throws Exception {
			//
			// TODO:
			//   Insert your code here...
			//
			// Example code to create and save a structure:
			//   com.cbody.cbody2 doc = com.cbody.cbody2.createDocument();			
			//   com.cbody.useridType root = doc.userid.append();
			//   ...
			//   doc.saveToFile("cbody1.xml", true);
			//
			// Example code to load and save a structure:
			//   com.cbody.cbody2 doc = com.cbody.cbody2.loadFromFile("cbody1.xml");
			//   com.cbody.useridType root = doc.userid.first();
			//   ...
			//   doc.saveToFile("cbody1.xml", true);


	}

	public static void main(String args[]) {
		try {
			System.out.println("cbody Test Application");
			example();
			System.out.println("OK");
			System.exit(0);
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}
}
