////////////////////////////////////////////////////////////////////////
//
// string2.java
//
// This file was generated by XMLSpy 2009sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

package com.cbody.xs;


public class string2 extends com.altova.xml.TypeBase
{
		public static com.altova.xml.meta.SimpleType getStaticInfo() { return new com.altova.xml.meta.SimpleType(com.cbody.cbody_TypeInfo.binder.getTypes()[com.cbody.cbody_TypeInfo._altova_ti_xs_altova_string2]); }
	
	public string2(org.w3c.dom.Node init)
	{
		super(init);
		instantiateMembers();
	}
	
	private void instantiateMembers()
	{

	}
	// Attributes


	// Elements
}
